export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number; // For discounted items
  images: string[];
  category: string;
  featured: boolean;
  inStock: boolean;
  stockQuantity: number;
  createdAt: string;
  updatedAt: string;
}

// Sample products data
export const products: Product[] = [
  {
    id: "1",
    name: "Professional Camera",
    description: "High-quality professional camera for photography enthusiasts. Features 4K video recording, 24MP sensor, and advanced autofocus system.",
    price: 1299.99,
    images: ["/images/products/product-1.jpg", "/images/products/product-2.jpg"],
    category: "Photography",
    featured: true,
    inStock: true,
    stockQuantity: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Graphic Design Software",
    description: "Industry-standard graphic design software with powerful tools for digital art, illustration, and photo editing.",
    price: 199.99,
    originalPrice: 249.99,
    images: ["/images/products/product-3.jpg", "/images/products/product-4.jpg"],
    category: "Software",
    featured: true,
    inStock: true,
    stockQuantity: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Drawing Tablet",
    description: "Professional drawing tablet with pressure sensitivity and wireless connectivity for digital artists.",
    price: 349.99,
    images: ["/images/products/product-5.jpg", "/images/products/product-6.jpg"],
    category: "Hardware",
    featured: false,
    inStock: true,
    stockQuantity: 15,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Studio Lighting Kit",
    description: "Complete studio lighting kit including 3 softbox lights, stands, and carrying case.",
    price: 199.99,
    originalPrice: 249.99,
    images: ["/images/products/product-7.jpg", "/images/products/product-8.jpg"],
    category: "Photography",
    featured: false,
    inStock: true,
    stockQuantity: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Premium Microphone",
    description: "Studio-quality condenser microphone for professional audio recording and podcasting.",
    price: 149.99,
    images: ["/images/products/product-9.jpg", "/images/products/product-10.jpg"],
    category: "Audio",
    featured: true,
    inStock: true,
    stockQuantity: 20,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Video Editing Software",
    description: "Professional video editing software with advanced features for content creators.",
    price: 299.99,
    originalPrice: 349.99,
    images: ["/images/products/product-1.jpg", "/images/products/product-2.jpg"],
    category: "Software",
    featured: false,
    inStock: true,
    stockQuantity: 100,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Wireless Headphones",
    description: "Premium wireless headphones with noise cancellation and studio-quality sound.",
    price: 249.99,
    images: ["/images/products/product-3.jpg", "/images/products/product-4.jpg"],
    category: "Audio",
    featured: true,
    inStock: true,
    stockQuantity: 25,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Portable SSD Drive",
    description: "Fast, portable SSD storage for creative professionals. 1TB capacity with USB-C connectivity.",
    price: 179.99,
    images: ["/images/products/product-5.jpg", "/images/products/product-6.jpg"],
    category: "Storage",
    featured: false,
    inStock: true,
    stockQuantity: 30,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "9",
    name: "Professional Tripod",
    description: "Sturdy, lightweight tripod for cameras and video equipment with fluid head for smooth panning.",
    price: 129.99,
    originalPrice: 159.99,
    images: ["/images/products/product-7.jpg", "/images/products/product-8.jpg"],
    category: "Photography",
    featured: false,
    inStock: true,
    stockQuantity: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Color Calibration Tool",
    description: "Professional color calibration tool for monitors and displays to ensure accurate color reproduction.",
    price: 199.99,
    images: ["/images/products/product-9.jpg", "/images/products/product-10.jpg"],
    category: "Accessories",
    featured: false,
    inStock: true,
    stockQuantity: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // كورسات برمجة عالمية
  {
    id: "11",
    name: "The Art of Mac Malware",
    description: "Unmask the secrets behind macOS exploitation. Think macOS is completely secure? This advanced and captivating course takes you deep into the world of Mac malware—how it's created, concealed, and detected. Whether you're a security researcher, tool developer, or cybersecurity enthusiast, this path is designed to sharpen your skills and reveal unseen aspects of macOS threats.",
    price: 94.99,
    originalPrice: 199.99,
    images: ["/images/courses/mac-malware.jpg", "/images/products/product-2.jpg"],
    category: "Courses",
    featured: true,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Android Malware",
    description: "Step into the dark world of Android hacking. In this course, you'll learn how malware is built, how hackers think, and how to reverse-engineer malicious apps like a pro. Master analysis tools, dynamic environments, and real-world evasion techniques used by advanced Android threats. If you're serious about cybersecurity — this is where your journey begins.",
    price: 89.99,
    originalPrice: 169.99,
    images: ["/images/courses/Android Malware.jpg", "/images/products/product-6.jpg"],
    category: "Courses",
    featured: true,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Data Science & Machine Learning Masterclass",
    description: "Complete data science bootcamp covering Python, NumPy, Pandas, Matplotlib, Scikit-Learn, TensorFlow, and practical machine learning projects. Includes career guidance and interview preparation.",
    price: 109.99,
    originalPrice: 199.99,
    images: ["/images/products/product-9.jpg", "/images/products/product-10.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "14",
    name: "JavaScript Algorithms & Data Structures",
    description: "Master technical interview preparation with comprehensive algorithms and data structures course. Learn problem-solving techniques and ace technical interviews at top tech companies.",
    price: 84.99,
    originalPrice: 169.99,
    images: ["/images/products/product-7.jpg", "/images/products/product-8.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "15",
    name: "React JS Masterclass - Build Modern Web Apps",
    description: "Become an expert React developer. Build complex, responsive, and performant web applications with React, Redux, React Router, and modern React features like Hooks and Context API.",
    price: 89.99,
    originalPrice: 179.99,
    images: ["/images/products/product-3.jpg", "/images/products/product-4.jpg"],
    category: "Courses",
    featured: true,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "16",
    name: "iOS App Development with Swift",
    description: "Learn iOS app development from scratch. Master Swift programming, UIKit, Core Data, and SwiftUI. Build and deploy 15 real-world iOS applications to the App Store.",
    price: 99.99,
    originalPrice: 189.99,
    images: ["/images/products/product-1.jpg", "/images/products/product-2.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "17",
    name: "DevOps Engineering & AWS Cloud Mastery",
    description: "Comprehensive DevOps engineering course covering Docker, Kubernetes, CI/CD pipelines, AWS Cloud services, infrastructure as code, and modern deployment strategies.",
    price: 119.99,
    originalPrice: 229.99,
    images: ["/images/products/product-5.jpg", "/images/products/product-6.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "18",
    name: "Cyber Security: From Zero to Hero",
    description: "Comprehensive cybersecurity course covering ethical hacking, penetration testing, network security, cryptography, and security best practices. Includes hands-on labs and real-world scenarios.",
    price: 124.99,
    originalPrice: 249.99,
    images: ["/images/products/product-9.jpg", "/images/products/product-10.jpg"],
    category: "Courses",
    featured: true,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "19",
    name: "Flutter & Dart: Build Multi-Platform Apps",
    description: "Master Flutter and Dart to build beautiful, responsive applications for iOS, Android, Web, and Desktop from a single codebase. Includes state management, Firebase integration, and app publishing.",
    price: 94.99,
    originalPrice: 179.99,
    images: ["/images/products/product-3.jpg", "/images/products/product-4.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "20",
    name: "Advanced Backend Development with Node.js",
    description: "Comprehensive Node.js course for building scalable, secure backend systems. Covers Express.js, authentication, RESTful APIs, GraphQL, database integration, deployment, and more.",
    price: 89.99,
    originalPrice: 169.99,
    images: ["/images/products/product-7.jpg", "/images/products/product-8.jpg"],
    category: "Courses",
    featured: false,
    inStock: true,
    stockQuantity: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

// Helper functions for product operations
export function getProductById(id: string): Product | undefined {
  return products.find(product => product.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(product => product.featured);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(product => product.category === category);
}

export function getDiscountedProducts(): Product[] {
  return products.filter(product => product.originalPrice !== undefined);
}

export function getAllCategories(): string[] {
  const categories = new Set(products.map(product => product.category));
  return Array.from(categories);
} 